import { CLIENT_CONFIG } from './config.js'; import {createSocketBoundary} from './socket.js'; import {createRenderer} from './renderer.js?v=phase3-turns-1'; import {createUI} from './ui.js?v=phase3-turns-1'; import {initWindGusts} from './wind-gusts.js?v=phase3-wind-1';
const canvas=document.getElementById('gameCanvas'),ui=createUI(),renderer=createRenderer(canvas,CLIENT_CONFIG),windGusts=initWindGusts(canvas),socketBoundary=createSocketBoundary();let activeSocket=null,playerId=null,currentRoom=null,disconnectHandlerBound=false;renderer.drawScaffold();ui.setClientStatus('READY');ui.setServerStatus(socketBoundary.isConfigured?'OFFLINE / ON DEMAND':'NOT CONFIGURED');ui.playerName.value=localStorage.getItem('orbital-artillery-player-name')||'';
const humanError=c=>({invalid_name:'Enter a player name first.',invalid_room_code:'Room code must contain 4 valid characters.',room_not_found:'That room does not exist.',room_full:'That room already has 8 players.',room_already_started:'That room has already started.',server_room_capacity:'The server has reached its temporary room limit.',room_action_rate_limited:'Too many lobby requests. Wait a moment.',already_in_room:'This tab is already inside a room.',not_in_room:'This tab is not currently inside a room.',invalid_team:'That team selection is invalid.',team_full:'That team already has 4 players.',teams_disabled:'Teams are disabled in Survival mode.',invalid_mode:'That game mode is invalid.',host_only:'Only the host can do that.',not_enough_players:'At least 2 players are required.',players_not_ready:'Every player must be READY.',both_teams_required:'Both teams need at least one player.',request_timeout:'The server did not answer in time.'}[c]||`Server rejected the request: ${c||'unknown_error'}`);
function renderRoom(r){currentRoom=r;ui.renderRoom(r,playerId);renderer.drawArena(r,playerId);windGusts.update(r);} async function ensureConnection(){ui.setBusy(true);ui.setServerStatus('CONNECTING');try{activeSocket=await socketBoundary.connect();ui.setServerStatus('CONNECTED');activeSocket.off('room_state');activeSocket.on('room_state',renderRoom);if(!disconnectHandlerBound){activeSocket.on('disconnect',()=>{disconnectHandlerBound=false;ui.setServerStatus('OFFLINE');ui.setMessage('Connection closed. Create or join again.');});disconnectHandlerBound=true;}return activeSocket;}finally{ui.setBusy(false);}}
function request(e,p={}){return new Promise(res=>activeSocket.timeout(8000).emit(e,p,(err,r)=>res(err?{ok:false,error:'request_timeout'}:r||{ok:false,error:'empty_response'})));}
function name(){const n=ui.playerName.value.trim().slice(0,20);if(n)localStorage.setItem('orbital-artillery-player-name',n);return n;}
async function createRoom(){const n=name();if(!n)return ui.setMessage('Enter a player name first.');await ensureConnection();const r=await request('create_room',{name:n});if(!r.ok)return ui.setMessage(humanError(r.error));playerId=r.playerId;renderRoom(r.room);ui.setMessage(`Room ${r.room.code} created.`);} async function joinRoom(){const n=name(),code=ui.roomCode.value.trim().toUpperCase();ui.roomCode.value=code;if(!n)return ui.setMessage('Enter a player name first.');if(code.length!==4)return ui.setMessage('Enter the 4-character room code.');await ensureConnection();const r=await request('join_room',{name:n,code});if(!r.ok)return ui.setMessage(humanError(r.error));playerId=r.playerId;renderRoom(r.room);ui.setMessage(`Joined room ${r.room.code}.`);}
async function mutate(event,payload,msg){const r=await request(event,payload);if(!r.ok)return ui.setMessage(humanError(r.error));renderRoom(r.room);if(msg)ui.setMessage(msg);}
ui.createRoomButton.addEventListener('click',createRoom);ui.joinRoomButton.addEventListener('click',joinRoom);ui.readyButton.addEventListener('click',()=>{const me=currentRoom?.players.find(p=>p.id===playerId);if(me)mutate('set_ready',{ready:!me.ready},!me.ready?'You are READY.':'Ready cancelled.');});ui.teamAButton.addEventListener('click',()=>mutate('set_team',{team:'A'},'Moved to Team A.'));ui.teamBButton.addEventListener('click',()=>mutate('set_team',{team:'B'},'Moved to Team B.'));ui.teamModeButton.addEventListener('click',()=>mutate('set_mode',{mode:'team'},'Team mode selected. READY states reset.'));ui.survivalModeButton.addEventListener('click',()=>mutate('set_mode',{mode:'survival'},'Survival mode selected. READY states reset.'));ui.startGameButton.addEventListener('click',()=>mutate('start_game',{},'Match countdown started.'));ui.roomCode.addEventListener('input',()=>ui.roomCode.value=ui.roomCode.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,4));window.addEventListener('pagehide',()=>{windGusts.destroy();socketBoundary.disconnect();});
console.info('Orbital Artillery Phase 3 turn loop client ready.');
