import { createRenderer as createPhase6fRenderer } from './renderer6f.js?v=phase7a-visual-base-1';

export function createRenderer(canvas, config) {
  const base=createPhase6fRenderer(canvas,config);
  const overlay=document.createElement('canvas');
  overlay.width=canvas.width;overlay.height=canvas.height;overlay.setAttribute('aria-hidden','true');
  Object.assign(overlay.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none',zIndex:'5'});
  canvas.parentElement?.appendChild(overlay);
  const ctx=overlay.getContext('2d');
  let room=null,frameId=null;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const lerp=(a,b,t)=>a+(b-a)*t;
  const COLORS={basic:'#fff0a8',heavy:'#ffad5c',triple:'#b5f2ff',cluster:'#ffb5d8',nuke:'#f3b0ff',airstrike:'#ffd58a'};
  function worldToScreen(x,y,view){return{x:(x-view.x)/view.width*overlay.width,y:(y-view.y)/view.height*overlay.height};}
  function projectilePosition(p,now=Date.now()){if(!p)return null;const secs=clamp(now-p.startedAt,0,p.durationMs??Math.max(1,p.impactAt-p.startedAt))/1000;return{x:p.startX+(p.vx??0)*secs+.5*(p.windAccel??0)*secs*secs,y:p.startY+(p.vy??0)*secs+.5*(p.gravity??0)*secs*secs};}
  function drawGlowOrb(screen,color,size=11){ctx.save();ctx.globalCompositeOperation='lighter';ctx.shadowColor=color;ctx.shadowBlur=26;ctx.fillStyle=color;ctx.beginPath();ctx.arc(screen.x,screen.y,size,0,Math.PI*2);ctx.fill();ctx.shadowBlur=8;ctx.fillStyle='#ffffff';ctx.beginPath();ctx.arc(screen.x,screen.y,Math.max(3,size*.34),0,Math.PI*2);ctx.fill();ctx.restore();}
  function drawFullBallistic(p,view,now,color,size=11){if(!p||now>=p.impactAt)return;const current=projectilePosition(p,now);if(!current)return;ctx.save();ctx.globalCompositeOperation='lighter';ctx.lineCap='round';ctx.lineJoin='round';const elapsed=Math.max(1,Math.min(now,p.impactAt)-p.startedAt),samples=Math.max(16,Math.min(90,Math.ceil(elapsed/55))),points=[];for(let i=0;i<=samples;i++){const t=p.startedAt+elapsed*(i/samples),q=projectilePosition(p,t);points.push(worldToScreen(q.x,q.y,view));}if(points.length>1){ctx.shadowColor=color;ctx.shadowBlur=16;ctx.strokeStyle=color;ctx.globalAlpha=.42;ctx.lineWidth=5;ctx.beginPath();points.forEach((s,i)=>i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y));ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#ffffff';ctx.globalAlpha=.34;ctx.lineWidth=1.5;ctx.beginPath();points.forEach((s,i)=>i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y));ctx.stroke();}const start=worldToScreen(p.startX,p.startY,view),age=now-p.startedAt;if(age<320){const pulse=1-age/320;ctx.globalAlpha=.75*pulse;ctx.fillStyle=color;ctx.beginPath();ctx.arc(start.x,start.y,8+20*pulse,0,Math.PI*2);ctx.fill();}ctx.restore();drawGlowOrb(worldToScreen(current.x,current.y,view),color,size);}
  function drawClusterChildren(q,view,now){const color=COLORS.cluster;for(const child of q.clusterImpacts??[]){const startAt=child.visualStartAt??(q.impactAt+1000);if(now<startAt||now>=child.impactAt)continue;const raw=clamp((now-startAt)/Math.max(1,child.impactAt-startAt),0,1),x=lerp(q.impactX,child.x,raw),y=lerp(q.impactY,child.y,raw)-Math.sin(Math.PI*raw)*190,p=worldToScreen(x,y,view),tailRaw=Math.max(0,raw-.16),tx=lerp(q.impactX,child.x,tailRaw),ty=lerp(q.impactY,child.y,tailRaw)-Math.sin(Math.PI*tailRaw)*190,t=worldToScreen(tx,ty,view);ctx.save();ctx.globalCompositeOperation='lighter';ctx.strokeStyle=color;ctx.shadowColor=color;ctx.shadowBlur=18;ctx.lineWidth=4;ctx.globalAlpha=.75;ctx.beginPath();ctx.moveTo(t.x,t.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();drawGlowOrb(p,color,8);}}
  function drawAirStrike(q,view,now){for(const shell of q.airStrikeShells??[]){const startAt=shell.visualStartAt??(shell.impactAt-3200);if(now<startAt||now>=shell.impactAt)continue;const raw=clamp((now-startAt)/Math.max(1,shell.impactAt-startAt),0,1),eased=raw*raw,x=shell.x,y=lerp(shell.startY,shell.y,eased),head=worldToScreen(x,y,view),tailY=lerp(shell.startY,shell.y,Math.max(0,raw-.13)**2),tail=worldToScreen(x,tailY,view);ctx.save();ctx.globalCompositeOperation='lighter';ctx.strokeStyle=COLORS.airstrike;ctx.shadowColor=COLORS.airstrike;ctx.shadowBlur=24;ctx.lineWidth=7;ctx.globalAlpha=.78;ctx.beginPath();ctx.moveTo(tail.x,tail.y);ctx.lineTo(head.x,head.y);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.globalAlpha=.72;ctx.beginPath();ctx.moveTo(tail.x,tail.y);ctx.lineTo(head.x,head.y);ctx.stroke();ctx.restore();drawGlowOrb(head,COLORS.airstrike,10);}}
  function drawProjectilePresentation(activeRoom,view){const q=activeRoom?.match?.projectile;if(activeRoom?.status!=='started'||!q)return;const now=Date.now(),type=q.weaponType??'basic';if(type==='airstrike'){drawAirStrike(q,view,now);return;}if(type==='triple'&&q.volley?.length){for(const v of q.volley)drawFullBallistic(v,view,now,COLORS.triple,10);return;}drawFullBallistic(q,view,now,COLORS[type]??COLORS.basic,type==='heavy'?14:type==='cluster'?13:type==='nuke'?12:11);if(type==='cluster')drawClusterChildren(q,view,now);}
  function loop(){ctx.clearRect(0,0,overlay.width,overlay.height);if(room?.arena){const view=base.getViewSnapshot?.();if(view)drawProjectilePresentation(room,view);}frameId=requestAnimationFrame(loop);}
  frameId=requestAnimationFrame(loop);
  return Object.freeze({drawScaffold(){room=null;ctx.clearRect(0,0,overlay.width,overlay.height);base.drawScaffold();},drawArena(nextRoom,nextLocalPlayerId=null){room=nextRoom;base.drawArena(nextRoom,nextLocalPlayerId);},getViewSnapshot(){return base.getViewSnapshot?.()??null;},destroy(){if(frameId)cancelAnimationFrame(frameId);frameId=null;overlay.remove();base.destroy?.();}});
}
