export function createRenderer(canvas, config) {
  if (!(canvas instanceof HTMLCanvasElement)) throw new TypeError('A valid game canvas is required.');
  canvas.width = config.internalWidth;
  canvas.height = config.internalHeight;
  const ctx = canvas.getContext('2d');

  let animationFrame = null, activeRoom = null, localPlayerId = null, cameraInitialized = false;
  let lastRoomStatus = null, lastTargetPlayerId = null, lastProjectileId = null, dragging = false, dragStart = null;
  const MIN_VIEW_UNITS = 1, MAX_VIEW_UNITS = 5, WORLD_UNITS = 5, OPENING_DIVE_MS = 1800, TURN_DIVE_MS = 900;
  const VEHICLE_WORLD_WIDTH = 28, VEHICLE_WORLD_HEIGHT = 15, PROJECTILE_GRAVITY = 480, PREVIEW_SIM_DT = 0.02, PREVIEW_MAX_SECONDS = 8, PREVIEW_DOT_INTERVAL = 0.12, IMPACT_EFFECT_MS = 900;

  const TERRAIN_HOLES = Object.freeze({ rolling: [], terraces: [[2430,2550]], twinpeaks: [[2390,2510]], basin: [[1140,1240],[3760,3860]], brokenridge: [[1010,1140],[2410,2550],[3860,3980]], islands: [[900,1040],[1920,2080],[2910,3070],[3960,4110]], canyon: [[2380,2580]] });
  const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
  const lerp = (a, b, t) => a + (b - a) * t;
  const smoothstep = t => t * t * (3 - 2 * t);
  const gaussian = (x, center, width, amplitude) => amplitude * Math.exp(-((x - center) ** 2) / width);
  const plateau = (x, left, right, y, fallback) => (x >= left && x <= right ? y : fallback);

  function baseTerrainY(preset, x) {
    switch (preset) {
      case 'terraces': { let y=3520+Math.sin(x/560)*100; y=plateau(x,330,900,3190,y); y=plateau(x,1040,1640,2920,y); y=plateau(x,1770,2350,3250,y); y=plateau(x,2630,3260,2820,y); y=plateau(x,3390,3970,3110,y); y=plateau(x,4110,4680,2870,y); return y; }
      case 'twinpeaks': { let y=3650-gaussian(x,1200,260000,850)-gaussian(x,3820,300000,900)+Math.sin(x/280)*60; if(x>650&&x<980)y=3000; if(x>1510&&x<1850)y=3170; if(x>3150&&x<3460)y=3090; if(x>4050&&x<4410)y=2890; return y; }
      case 'basin': { let y=2870+gaussian(x,2500,850000,690)+Math.sin(x/410)*65; if(x>420&&x<950)y=2750; if(x>1320&&x<1760)y=3160; if(x>3240&&x<3680)y=3160; if(x>4050&&x<4580)y=2750; return y; }
      case 'brokenridge': { let y=3490+Math.sin(x/210)*170+Math.sin(x/690+1.1)*130; if(x>420&&x<900)y=3070; if(x>1260&&x<1720)y=2740; if(x>1900&&x<2320)y=3260; if(x>2700&&x<3160)y=2860; if(x>3330&&x<3770)y=3180; if(x>4140&&x<4620)y=2780; return y; }
      case 'islands': if(x<900)return 3100-gaussian(x,520,90000,260); if(x<1920)return 2840-gaussian(x,1470,125000,190); if(x<2910)return 3260-gaussian(x,2480,130000,320); if(x<3960)return 2760-gaussian(x,3470,135000,220); return 3160-gaussian(x,4540,100000,280);
      case 'canyon': { let y=2920+Math.min(Math.abs(x-2500)*0.28,700); if(x>420&&x<980)y=2700; if(x>1120&&x<1640)y=3030; if(x>1800&&x<2260)y=3380; if(x>2740&&x<3200)y=3380; if(x>3360&&x<3880)y=3030; if(x>4020&&x<4580)y=2700; return y; }
      default: { let y=3440+Math.sin(x/470)*165+Math.sin(x/980+0.7)*95; if(x>700&&x<1120)y=3140; if(x>1760&&x<2140)y=2920; if(x>2840&&x<3240)y=3170; if(x>3890&&x<4320)y=2860; return y; }
    }
  }

  function terrainY(x, room = activeRoom) {
    const arena=room?.arena, worldWidth=arena?.worldWidth??5000, worldHeight=arena?.worldHeight??5000, px=clamp(x,0,worldWidth), preset=room?.terrainPreset||arena?.terrainPreset||'rolling';
    if((TERRAIN_HOLES[preset]??[]).some(([left,right])=>px>=left&&px<=right))return worldHeight;
    let y=baseTerrainY(preset,px); for(const crater of arena?.craters??[]){const dx=Math.abs(px-crater.x);if(dx<crater.radius)y+=crater.depth*Math.sqrt(Math.max(0,1-(dx/crater.radius)**2));} return clamp(y,120,worldHeight);
  }

  const camera={centerX:2500,centerY:2500,viewUnits:MAX_VIEW_UNITS,targetCenterX:2500,targetCenterY:2500,targetViewUnits:MAX_VIEW_UNITS,manual:false,transition:null,projectileFollow:false};
  function drawBackground(){const g=ctx.createLinearGradient(0,0,0,canvas.height);g.addColorStop(0,'#071224');g.addColorStop(.62,'#0a1221');g.addColorStop(1,'#02040a');ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.globalAlpha=.55;for(let i=0;i<90;i+=1){const x=(i*233+91)%canvas.width,y=(i*137+47)%Math.max(430,canvas.height*.62),s=i%9===0?2:1;ctx.fillStyle='#8cb4ff';ctx.fillRect(x,y,s,s);}ctx.restore();}
  function cancelLoop(){if(animationFrame)cancelAnimationFrame(animationFrame);animationFrame=null;}
  function drawScaffold(){cancelLoop();activeRoom=null;cameraInitialized=false;lastRoomStatus=null;lastTargetPlayerId=null;lastProjectileId=null;camera.transition=null;camera.projectileFollow=false;ctx.clearRect(0,0,canvas.width,canvas.height);drawBackground();ctx.fillStyle='#18243d';ctx.beginPath();ctx.moveTo(0,canvas.height*.72);ctx.quadraticCurveTo(canvas.width*.2,canvas.height*.58,canvas.width*.38,canvas.height*.70);ctx.quadraticCurveTo(canvas.width*.58,canvas.height*.84,canvas.width*.72,canvas.height*.63);ctx.quadraticCurveTo(canvas.width*.86,canvas.height*.50,canvas.width,canvas.height*.68);ctx.lineTo(canvas.width,canvas.height);ctx.lineTo(0,canvas.height);ctx.fill();}
  function activeDeathMotion(room,now=Date.now()){return room?.players?.find(player=>player.motion?.endsAt>now&&['jump','fall','voidJump'].includes(player.motion.type)&&player.spawn?.y>(room.arena?.worldHeight??5000))??null;}
  function cameraTarget(room){const falling=room?.status==='finished'?activeDeathMotion(room):null;if(falling)return falling;const id=room.camera?.targetPlayerId||room.match?.activePlayerId||localPlayerId;return room.players.find(p=>p.id===id)||room.players.find(p=>p.id===localPlayerId)||room.players.find(p=>p.alive!==false)||room.players[0]||null;}
  function viewSize(arena,units=camera.viewUnits){const f=clamp(units,MIN_VIEW_UNITS,MAX_VIEW_UNITS)/WORLD_UNITS;return{width:arena.worldWidth*f,height:arena.worldHeight*f};}
  function clampCenter(arena,x,y,units=camera.viewUnits){const s=viewSize(arena,units),hw=s.width/2,hh=s.height/2;return{x:clamp(x,hw,arena.worldWidth-hw),y:clamp(y,hh,arena.worldHeight-hh)};}
  function clampCamera(arena){let c=clampCenter(arena,camera.centerX,camera.centerY,camera.viewUnits);camera.centerX=c.x;camera.centerY=c.y;c=clampCenter(arena,camera.targetCenterX,camera.targetCenterY,camera.targetViewUnits);camera.targetCenterX=c.x;camera.targetCenterY=c.y;}
  function setFullMap(room){camera.manual=false;camera.projectileFollow=false;camera.transition=null;camera.viewUnits=MAX_VIEW_UNITS;camera.targetViewUnits=MAX_VIEW_UNITS;camera.centerX=room.arena.worldWidth/2;camera.centerY=room.arena.worldHeight/2;camera.targetCenterX=camera.centerX;camera.targetCenterY=camera.centerY;cameraInitialized=true;clampCamera(room.arena);}
  function setFollowTarget(room,immediate=false){const t=cameraTarget(room);if(!t?.spawn||!room.arena)return;const pos=visualPlayerPosition(t);camera.targetCenterX=pos.x;camera.targetCenterY=pos.y;if(immediate){camera.centerX=pos.x;camera.centerY=pos.y;}clampCamera(room.arena);}
  function beginTargetTransition(room,durationMs,now=performance.now()){const t=cameraTarget(room);if(!t?.spawn)return;const pos=visualPlayerPosition(t),d=clampCenter(room.arena,pos.x,pos.y,MIN_VIEW_UNITS);camera.manual=false;camera.projectileFollow=false;camera.transition={startedAt:now,endsAt:now+durationMs,fromCenterX:camera.centerX,fromCenterY:camera.centerY,fromViewUnits:camera.viewUnits,toCenterX:d.x,toCenterY:d.y,toViewUnits:MIN_VIEW_UNITS};camera.targetCenterX=d.x;camera.targetCenterY=d.y;camera.targetViewUnits=MIN_VIEW_UNITS;}
  function projectilePosition(p,now=Date.now()){if(!p)return null;const ms=clamp(now-p.startedAt,0,p.durationMs),t=ms/1000;return{x:p.startX+p.vx*t+.5*p.windAccel*t*t,y:p.startY+p.vy*t+.5*p.gravity*t*t,impact:now>=p.impactAt};}
  function controlsLocked(now=performance.now()){return ['lobby','countdown','finished'].includes(activeRoom?.status)||Boolean(camera.transition&&now<camera.transition.endsAt)||Boolean(activeRoom?.match?.projectile);}

  function ensureCameraState(room){if(!room?.arena)return;const targetId=room.camera?.targetPlayerId||room.match?.activePlayerId||null,projectileId=room.match?.projectile?.id||null;if(room.status==='lobby'){if(!cameraInitialized||lastRoomStatus!=='lobby')setFullMap(room);lastRoomStatus='lobby';lastTargetPlayerId=null;lastProjectileId=null;return;}if(!cameraInitialized){if(room.status==='countdown')setFullMap(room);else{camera.viewUnits=MIN_VIEW_UNITS;camera.targetViewUnits=MIN_VIEW_UNITS;setFollowTarget(room,true);cameraInitialized=true;}}if(lastRoomStatus==='lobby'&&room.status==='countdown')setFullMap(room);if(lastRoomStatus==='countdown'&&room.status==='started')beginTargetTransition(room,OPENING_DIVE_MS);else if(room.status==='started'&&lastTargetPlayerId&&targetId&&targetId!==lastTargetPlayerId&&!projectileId)beginTargetTransition(room,TURN_DIVE_MS);if(projectileId&&projectileId!==lastProjectileId){camera.manual=false;camera.transition=null;camera.projectileFollow=true;camera.targetViewUnits=MIN_VIEW_UNITS;}if(!projectileId&&lastProjectileId)camera.projectileFollow=false;if(room.status==='finished'&&lastRoomStatus!=='finished'){camera.manual=false;camera.projectileFollow=false;camera.transition=null;camera.targetViewUnits=MIN_VIEW_UNITS;setFollowTarget(room,false);}lastRoomStatus=room.status;if(targetId)lastTargetPlayerId=targetId;lastProjectileId=projectileId;}
  function currentView(arena){const s=viewSize(arena);return{x:camera.centerX-s.width/2,y:camera.centerY-s.height/2,width:s.width,height:s.height};}
  function worldToScreen(x,y,v){return{x:(x-v.x)/v.width*canvas.width,y:(y-v.y)/v.height*canvas.height};}
  function screenToWorld(x,y,arena){const v=currentView(arena);return{x:v.x+x/canvas.width*v.width,y:v.y+y/canvas.height*v.height};}
  function updateCamera(room,now){if(!room?.arena||room.status==='lobby'||room.status==='countdown')return;const p=room.match?.projectile;if(p&&camera.projectileFollow){const pos=projectilePosition(p);if(pos){const c=clampCenter(room.arena,pos.x,pos.y,MIN_VIEW_UNITS);camera.targetCenterX=c.x;camera.targetCenterY=c.y;camera.targetViewUnits=MIN_VIEW_UNITS;camera.centerX=lerp(camera.centerX,c.x,.22);camera.centerY=lerp(camera.centerY,c.y,.22);camera.viewUnits=lerp(camera.viewUnits,MIN_VIEW_UNITS,.18);clampCamera(room.arena);return;}}if(camera.transition){const tr=camera.transition,raw=clamp((now-tr.startedAt)/(tr.endsAt-tr.startedAt),0,1),t=smoothstep(raw);camera.centerX=lerp(tr.fromCenterX,tr.toCenterX,t);camera.centerY=lerp(tr.fromCenterY,tr.toCenterY,t);camera.viewUnits=lerp(tr.fromViewUnits,tr.toViewUnits,t);if(raw>=1){camera.centerX=tr.toCenterX;camera.centerY=tr.toCenterY;camera.viewUnits=tr.toViewUnits;camera.targetCenterX=tr.toCenterX;camera.targetCenterY=tr.toCenterY;camera.targetViewUnits=tr.toViewUnits;camera.transition=null;}clampCamera(room.arena);return;}if(!camera.manual)setFollowTarget(room,false);camera.centerX=lerp(camera.centerX,camera.targetCenterX,.16);camera.centerY=lerp(camera.centerY,camera.targetCenterY,.16);camera.viewUnits=lerp(camera.viewUnits,camera.targetViewUnits,.14);clampCamera(room.arena);}

  function visualPlayerPosition(player,now=Date.now()){const m=player.motion;if(!m||now>=m.endsAt)return player.spawn;const raw=clamp((now-m.startedAt)/(m.endsAt-m.startedAt),0,1);if(m.type==='voidJump'){const lift=.28;if(raw<lift){const t=raw/lift,x=lerp(m.fromX,m.toX,smoothstep(t)),y=lerp(m.fromY,m.fromY-30,t)-Math.sin(Math.PI*t)*(m.apex||150);return{...player.spawn,x,y};}const t=(raw-lift)/(1-lift),x=m.toX,y=lerp(m.fromY-30,m.toY,t*t);return{...player.spawn,x,y};}const x=lerp(m.fromX,m.toX,raw),baseY=lerp(m.fromY,m.toY,raw),arc=m.type==='jump'?Math.sin(Math.PI*raw)*(m.apex||0):0;return{...player.spawn,x,y:baseY-arc};}
  function drawTerrain(room,view){const step=5;ctx.save();ctx.fillStyle='#18243d';for(let sx=0;sx<canvas.width;sx+=step){const wx=view.x+(sx/canvas.width)*view.width,wy=terrainY(wx,room);if(wy>=room.arena.worldHeight-1)continue;const sy=worldToScreen(wx,wy,view).y;ctx.fillRect(sx,sy,step+1,canvas.height-sy);}ctx.restore();ctx.save();ctx.strokeStyle='rgba(140,180,255,.20)';ctx.lineWidth=1;ctx.beginPath();let drawing=false;for(let sx=0;sx<=canvas.width;sx+=step){const wx=view.x+(sx/canvas.width)*view.width,wy=terrainY(wx,room);if(wy>=room.arena.worldHeight-1){drawing=false;continue;}const sy=worldToScreen(wx,wy,view).y;if(!drawing){ctx.moveTo(sx,sy);drawing=true;}else ctx.lineTo(sx,sy);}ctx.stroke();ctx.restore();}
  function drawPreviewSpawns(room,view){if(room.status!=='lobby')return;ctx.save();(room.arena?.previewSpawns??[]).forEach((x,index)=>{const y=terrainY(x,room);if(y>=room.arena.worldHeight-1)return;const p=worldToScreen(x,y-18,view);ctx.strokeStyle='rgba(255,232,154,.75)';ctx.fillStyle='rgba(255,232,154,.13)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,13,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#ffe89a';ctx.font='700 11px ui-monospace,monospace';ctx.textAlign='center';ctx.fillText(String(index+1),p.x,p.y+4);});ctx.restore();}

  function drawVehicle(room,player,pos,view,local,active){if(!pos)return;const s=worldToScreen(pos.x,pos.y,view);if(s.x<-90||s.x>canvas.width+90||s.y<-90||s.y>canvas.height+90)return;const pxX=canvas.width/view.width,pxY=canvas.height/view.height,w=clamp(VEHICLE_WORLD_WIDTH*pxX,8,52),h=clamp(VEHICLE_WORLD_HEIGHT*pxY,5,30),wr=clamp(h*.28,2,7),cl=clamp(w*.48,6,22),ct=clamp(h*.16,2,5),angle=active?(room.match?.aimAngle??45):15;
    ctx.save();ctx.translate(s.x,s.y);ctx.scale(pos.facing||1,1);ctx.globalAlpha=player.alive===false?.48:1;ctx.fillStyle=room.mode==='survival'?'#d6b4ff':player.team==='A'?'#8cb4ff':'#ff9aa8';ctx.strokeStyle=active?'#ffe89a':local?'#ffffff':'rgba(231,237,255,.55)';ctx.lineWidth=active?3:local?2.5:1.5;ctx.beginPath();ctx.roundRect(-w/2,-h*.62,w,h,Math.max(2,h*.25));ctx.fill();ctx.stroke();ctx.fillStyle='#08101d';ctx.beginPath();ctx.arc(-w*.27,h*.24,wr,0,Math.PI*2);ctx.arc(w*.27,h*.24,wr,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(w*.08,-h*.72);ctx.rotate(-angle*Math.PI/180);ctx.fillRect(0,-ct/2,cl,ct);ctx.restore();ctx.restore();
    if(camera.viewUnits<=3.25||active||local){const offset=Math.max(30,h*2.25),hp=clamp(player.hp??100,0,player.maxHp??100),maxHp=player.maxHp??100,barW=Math.max(46,Math.min(82,w*2.25));ctx.textAlign='center';ctx.fillStyle='#e7edff';ctx.font='700 15px ui-monospace,monospace';ctx.fillText(player.name,s.x,s.y-offset);ctx.fillStyle='rgba(4,8,16,.82)';ctx.fillRect(s.x-barW/2,s.y-offset+7,barW,7);ctx.fillStyle=hp>50?'#9be7b0':hp>25?'#ffe89a':'#ff9aa8';ctx.fillRect(s.x-barW/2,s.y-offset+7,barW*(hp/maxHp),7);ctx.strokeStyle='rgba(231,237,255,.45)';ctx.strokeRect(s.x-barW/2,s.y-offset+7,barW,7);ctx.font='700 10px ui-monospace,monospace';ctx.fillStyle=player.alive===false?'#ff9aa8':active?'#ffe89a':'#8cb4ff';const role=player.alive===false?'OUT':room.mode==='survival'?'SURVIVAL':`TEAM ${player.team}`,flags=`${local?' // YOU':''}${active?' // ACTIVE':''}`;ctx.fillText(`${role}${flags} // HP ${hp}`,s.x,s.y-offset+27);const damageAge=Date.now()-(player.lastDamage?.at??0);if(player.lastDamage&&damageAge>=0&&damageAge<1200){const t=damageAge/1200;ctx.globalAlpha=1-t;ctx.fillStyle='#ff9aa8';ctx.font='800 18px ui-monospace,monospace';ctx.fillText(`-${player.lastDamage.amount}`,s.x,s.y-offset-12-t*28);ctx.globalAlpha=1;}}
  }

  function drawAimPreview(room,view){if(room.status!=='started'||room.match?.projectile||room.match?.activePlayerId!==localPlayerId)return;const player=room.players.find(p=>p.id===localPlayerId);if(!player?.spawn||player.alive===false)return;const pos=visualPlayerPosition(player),facing=pos.facing||1,angle=room.match?.aimAngle??45,power=room.match?.aimPower??55,rad=angle*Math.PI/180,speed=320+power*9,startX=pos.x+facing*24,startY=pos.y-24,vx=Math.cos(rad)*speed*facing,vy=-Math.sin(rad)*speed,wind=(room.match?.wind?.signed??0)*1.5,dots=[];let nextDot=0,impact=null;for(let t=PREVIEW_SIM_DT;t<=PREVIEW_MAX_SECONDS;t+=PREVIEW_SIM_DT){const x=startX+vx*t+.5*wind*t*t,y=startY+vy*t+.5*PROJECTILE_GRAVITY*t*t;if(t>=nextDot){dots.push({x,y});nextDot+=PREVIEW_DOT_INTERVAL;}if(x<0||x>room.arena.worldWidth||y>room.arena.worldHeight){impact={x:clamp(x,0,room.arena.worldWidth),y};break;}let hit=false;for(const target of room.players){if(target.alive===false||!target.spawn||(target.id===player.id&&t<.14))continue;if(Math.hypot(x-target.spawn.x,y-(target.spawn.y-10))<=26){impact={x,y};hit=true;break;}}if(hit)break;const surface=terrainY(x,room);if(surface<room.arena.worldHeight&&t>.08&&y>=surface){impact={x:clamp(x,0,room.arena.worldWidth),y:surface};break;}}ctx.save();ctx.fillStyle='rgba(255,232,154,.66)';dots.forEach((dot,i)=>{const p=worldToScreen(dot.x,dot.y,view);if(p.x<-12||p.x>canvas.width+12||p.y<-12||p.y>canvas.height+12)return;ctx.globalAlpha=.34+Math.min(i/Math.max(dots.length,1),1)*.34;ctx.beginPath();ctx.arc(p.x,p.y,i%4===0?3.1:2.2,0,Math.PI*2);ctx.fill();});if(impact){const m=worldToScreen(impact.x,impact.y,view);ctx.globalAlpha=.82;ctx.strokeStyle='#ffe89a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(m.x,m.y,9,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(m.x-13,m.y);ctx.lineTo(m.x+13,m.y);ctx.moveTo(m.x,m.y-13);ctx.lineTo(m.x,m.y+13);ctx.stroke();}ctx.restore();}
  function drawProjectile(room,view){const p=room.match?.projectile;if(!p)return;const now=Date.now(),pos=projectilePosition(p,now);if(!pos)return;ctx.save();ctx.strokeStyle='rgba(255,232,154,.38)';ctx.lineWidth=2;ctx.beginPath();const trailStart=Math.max(p.startedAt,now-420);for(let sample=trailStart;sample<=Math.min(now,p.impactAt);sample+=35){const q=projectilePosition(p,sample),s=worldToScreen(q.x,q.y,view);if(sample===trailStart)ctx.moveTo(s.x,s.y);else ctx.lineTo(s.x,s.y);}ctx.stroke();const s=worldToScreen(pos.x,pos.y,view);ctx.fillStyle='#ffe89a';ctx.beginPath();ctx.arc(s.x,s.y,7,0,Math.PI*2);ctx.fill();if(now>=p.impactAt){const impact=worldToScreen(p.impactX,p.impactY,view),age=clamp((now-p.impactAt)/IMPACT_EFFECT_MS,0,1),fade=1-age;const glow=ctx.createRadialGradient(impact.x,impact.y,0,impact.x,impact.y,85+age*35);glow.addColorStop(0,`rgba(255,245,190,${.44*fade})`);glow.addColorStop(.3,`rgba(255,184,90,${.26*fade})`);glow.addColorStop(1,'rgba(255,120,60,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(impact.x,impact.y,90+age*35,0,Math.PI*2);ctx.fill();ctx.strokeStyle=`rgba(255,240,168,${.92*fade})`;ctx.lineWidth=5-3*age;ctx.beginPath();ctx.arc(impact.x,impact.y,12+age*70,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=`rgba(255,145,100,${.72*fade})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(impact.x,impact.y,30+age*105,0,Math.PI*2);ctx.stroke();for(let i=0;i<14;i+=1){const a=i/14*Math.PI*2+0.31,inner=18+age*22,outer=42+age*(70+(i%4)*9);ctx.strokeStyle=`rgba(255,210,135,${(.72-(i%3)*.12)*fade})`;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(impact.x+Math.cos(a)*inner,impact.y+Math.sin(a)*inner);ctx.lineTo(impact.x+Math.cos(a)*outer,impact.y+Math.sin(a)*outer);ctx.stroke();}if(age<.18){ctx.fillStyle=`rgba(255,248,220,${(.18-age)*1.8})`;ctx.fillRect(0,0,canvas.width,canvas.height);}}ctx.restore();}

  function nextPlayer(room){const order=room.match?.turnOrder??[];if(!order.length||room.match?.turnIndex==null)return null;for(let o=1;o<=order.length;o+=1){const id=order[(room.match.turnIndex+o)%order.length],p=room.players.find(e=>e.id===id);if(p?.alive!==false)return p;}return null;}
  function visiblePlayerCount(room,view){return room.players.filter(p=>p.spawn&&p.spawn.x>=view.x&&p.spawn.x<=view.x+view.width&&p.spawn.y>=view.y&&p.spawn.y<=view.y+view.height).length;}
  function drawCameraHud(room,target,view){if(room.status==='lobby')return;const local=room.players.find(p=>p.id===localPlayerId),zoom=camera.viewUnits.toFixed(camera.viewUnits%1<.03?0:1),mode=room.mode==='survival'?'SURVIVAL':'TEAM',locked=controlsLocked(),falling=room.status==='finished'&&activeDeathMotion(room),viewMode=room.match?.projectile?'PROJECTILE CAM':falling?'FALL CAM':room.status==='finished'?'MATCH ENDED':locked?'CAMERA LOCKED':camera.manual?'FREE CAMERA':'FOLLOW CAMERA';ctx.textAlign='left';ctx.fillStyle='rgba(7,10,18,.84)';ctx.fillRect(24,24,610,126);ctx.strokeStyle='rgba(155,184,255,.25)';ctx.strokeRect(24,24,610,126);ctx.fillStyle='#8cb4ff';ctx.font='700 13px ui-monospace,monospace';ctx.fillText(`PHASE 5B // ${mode} // ${viewMode}`,42,50);ctx.fillStyle='#e7edff';ctx.font='700 14px ui-monospace,monospace';ctx.fillText(`OBSERVING: ${target?.name??'—'}${target?.id===localPlayerId?' (YOU)':''}`,42,76);ctx.fillStyle='#8995b8';ctx.font='12px ui-monospace,monospace';ctx.fillText(`view ${zoom}x${zoom} of world 5x5 // ${room.arena.terrainName??room.terrainPreset}`,42,100);ctx.fillText(locked?'camera controls temporarily locked':'drag = pan // wheel = zoom 1x1..5x5 // double click = follow active',42,122);ctx.fillText(`you: ${local?.name??'—'} // visible players: ${visiblePlayerCount(room,view)}/${room.players.length}`,42,142);}
  function drawTurnHud(room){if(room.status!=='started'||!room.match?.activePlayerId)return;const active=room.players.find(p=>p.id===room.match.activePlayerId),next=nextPlayer(room),projectile=room.match.projectile,remaining=(Math.max(0,(room.match.turnEndsAt??Date.now())-Date.now())/1000).toFixed(1),wind=room.match.wind,arrow=wind?.direction==='left'?'←':wind?.direction==='right'?'→':'·',localTurn=room.match.activePlayerId===localPlayerId,alive=room.players.filter(p=>p.alive!==false).length,x=canvas.width-444;ctx.textAlign='left';ctx.fillStyle=localTurn?'rgba(30,42,22,.90)':'rgba(7,10,18,.88)';ctx.fillRect(x,24,420,205);ctx.strokeStyle=localTurn?'rgba(166,255,135,.55)':'rgba(255,232,154,.35)';ctx.strokeRect(x,24,420,205);ctx.fillStyle=localTurn?'#a6ff87':'#ffe89a';ctx.font='800 16px ui-monospace,monospace';ctx.fillText(projectile?'SHOT IN FLIGHT':localTurn?'YOUR TURN':'SPECTATING',x+18,50);ctx.fillStyle='#e7edff';ctx.font='700 14px ui-monospace,monospace';ctx.fillText(`TURN ${room.match.turnNumber??1} // ACTIVE: ${active?.name??'—'} // HP ${active?.hp??0}`,x+18,78);ctx.fillStyle='#8cb4ff';ctx.font='800 22px ui-monospace,monospace';ctx.fillText(projectile?`IMPACT ${remaining}s`:`TIME ${remaining}s`,x+18,108);ctx.fillStyle='#e7edff';ctx.font='700 14px ui-monospace,monospace';ctx.fillText(`WIND ${arrow} ${wind?.strength??0}`,x+220,108);ctx.fillStyle='#8995b8';ctx.font='12px ui-monospace,monospace';ctx.fillText(`MOVE ±${room.match.movementRadius??0} // JUMPS ${room.match.jumpsRemaining??0}/2`,x+18,136);ctx.fillText(`ANGLE ${Math.round(room.match.aimAngle??45)}° // POWER ${Math.round(room.match.aimPower??55)}%`,x+220,136);ctx.fillText(`NEXT: ${next?.name??'—'} // ALIVE ${alive}/${room.players.length}`,x+18,160);ctx.fillText(`CRATERS ${room.arena.craters?.length??0} // ${room.arena.terrainName??room.terrainPreset}`,x+18,183);ctx.fillText(localTurn&&!projectile?'A/D move // SPACE jump // W/S angle // Q/E power // F fire':projectile?'Explosion deals distance-based damage.':'Wait for your turn; camera remains available.',x+18,208);}
  function drawLobbyHud(room){if(room.status!=='lobby')return;ctx.save();ctx.textAlign='center';ctx.fillStyle='rgba(7,10,18,.78)';ctx.fillRect(canvas.width/2-330,26,660,82);ctx.strokeStyle='rgba(140,180,255,.28)';ctx.strokeRect(canvas.width/2-330,26,660,82);ctx.fillStyle='#e7edff';ctx.font='800 18px ui-monospace,monospace';ctx.fillText(room.arena.terrainName??room.terrainPreset,canvas.width/2,56);ctx.fillStyle='#8cb4ff';ctx.font='700 12px ui-monospace,monospace';ctx.fillText('LIVE TERRAIN PREVIEW // numbered markers show approximately even player spacing',canvas.width/2,80);ctx.fillStyle='#8995b8';ctx.fillText('Host can change terrain before READY / START',canvas.width/2,98);ctx.restore();}
  function drawCountdownOverlay(room){const elapsed=Date.now()-(room.match?.countdownStartedAt??Date.now()),count=6-Math.floor(elapsed/1000),label=elapsed<1000?'GET READY':count>0?String(count):'START';ctx.fillStyle='rgba(2,4,10,.44)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.textAlign='center';ctx.fillStyle='#e7edff';ctx.font='800 76px system-ui,sans-serif';ctx.fillText(label,canvas.width/2,canvas.height/2);ctx.font='700 18px ui-monospace,monospace';ctx.fillStyle='#8cb4ff';ctx.fillText(`${room.arena.terrainName??room.terrainPreset} // FULL MAP OVERVIEW`,canvas.width/2,canvas.height/2+54);ctx.font='12px ui-monospace,monospace';ctx.fillStyle='#8995b8';ctx.fillText('100 HP // destructible terrain // last player or team standing wins',canvas.width/2,canvas.height/2+82);}
  function drawResultOverlay(room){if(room.status!=='finished'||!room.match?.result||activeDeathMotion(room))return;const result=room.match.result;let title='DRAW',subtitle='No player survived.';if(!result.draw&&result.type==='survival'){title=`${result.winnerName??'PLAYER'} WINS`;subtitle='Last vehicle standing.';}else if(!result.draw&&result.type==='team'){title=`TEAM ${result.winnerTeam} WINS`;subtitle='Enemy team eliminated.';}ctx.save();ctx.fillStyle='rgba(2,4,10,.62)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.textAlign='center';ctx.fillStyle='#ffe89a';ctx.font='800 64px system-ui,sans-serif';ctx.fillText(title,canvas.width/2,canvas.height/2-10);ctx.fillStyle='#e7edff';ctx.font='700 18px ui-monospace,monospace';ctx.fillText(subtitle,canvas.width/2,canvas.height/2+34);ctx.fillStyle='#8995b8';ctx.font='12px ui-monospace,monospace';ctx.fillText('MATCH COMPLETE // create a new room for another battle',canvas.width/2,canvas.height/2+66);ctx.restore();}

  function drawWorld(room){const view=currentView(room.arena),target=cameraTarget(room);ctx.clearRect(0,0,canvas.width,canvas.height);drawBackground();drawTerrain(room,view);drawPreviewSpawns(room,view);if(room.status==='started')drawAimPreview(room,view);for(const player of room.players){if(!player.spawn)continue;drawVehicle(room,player,visualPlayerPosition(player),view,player.id===localPlayerId,player.id===room.match?.activePlayerId);}if(room.status==='started')drawProjectile(room,view);drawCameraHud(room,target,view);drawTurnHud(room);drawLobbyHud(room);drawResultOverlay(room);}
  function frame(now){if(!activeRoom?.arena)return;ensureCameraState(activeRoom);updateCamera(activeRoom,now);drawWorld(activeRoom);if(activeRoom.status==='countdown')drawCountdownOverlay(activeRoom);animationFrame=requestAnimationFrame(frame);}
  function drawArena(room,nextLocalPlayerId=null){localPlayerId=nextLocalPlayerId;activeRoom=room;if(!room?.arena||!['lobby','countdown','started','finished'].includes(room.status)){drawScaffold();return;}ensureCameraState(room);if(!animationFrame)animationFrame=requestAnimationFrame(frame);}
  function pointerPosition(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)/rect.width*canvas.width,y:(event.clientY-rect.top)/rect.height*canvas.height};}
  canvas.addEventListener('pointerdown',event=>{if(!activeRoom?.arena||controlsLocked())return;dragging=true;canvas.setPointerCapture?.(event.pointerId);const p=pointerPosition(event);dragStart={...p,centerX:camera.centerX,centerY:camera.centerY};camera.manual=true;});
  canvas.addEventListener('pointermove',event=>{if(!dragging||!dragStart||!activeRoom?.arena||controlsLocked())return;const p=pointerPosition(event),size=viewSize(activeRoom.arena);camera.targetCenterX=dragStart.centerX-(p.x-dragStart.x)/canvas.width*size.width;camera.targetCenterY=dragStart.centerY-(p.y-dragStart.y)/canvas.height*size.height;camera.centerX=camera.targetCenterX;camera.centerY=camera.targetCenterY;clampCamera(activeRoom.arena);});
  function stopDragging(event){dragging=false;dragStart=null;if(event?.pointerId!=null)canvas.releasePointerCapture?.(event.pointerId);}canvas.addEventListener('pointerup',stopDragging);canvas.addEventListener('pointercancel',stopDragging);canvas.addEventListener('pointerleave',event=>{if(dragging&&event.buttons===0)stopDragging(event);});
  canvas.addEventListener('wheel',event=>{if(!activeRoom?.arena||controlsLocked())return;event.preventDefault();const arena=activeRoom.arena,p=pointerPosition(event),before=screenToWorld(p.x,p.y,arena),direction=event.deltaY>0?1:-1,nextUnits=clamp(camera.viewUnits+direction*.35,MIN_VIEW_UNITS,MAX_VIEW_UNITS);if(Math.abs(nextUnits-camera.viewUnits)<.001)return;camera.manual=true;camera.viewUnits=nextUnits;camera.targetViewUnits=nextUnits;const newSize=viewSize(arena,nextUnits);camera.centerX=before.x-(p.x/canvas.width-.5)*newSize.width;camera.centerY=before.y-(p.y/canvas.height-.5)*newSize.height;camera.targetCenterX=camera.centerX;camera.targetCenterY=camera.centerY;clampCamera(arena);},{passive:false});
  canvas.addEventListener('dblclick',()=>{if(!activeRoom?.arena||controlsLocked())return;camera.manual=false;camera.targetViewUnits=MIN_VIEW_UNITS;setFollowTarget(activeRoom,false);});
  return Object.freeze({drawScaffold,drawArena});
}
