export function createUI(){
 const q=id=>document.getElementById(id); const clientStatus=q('clientStatus'),serverStatus=q('serverStatus'),playerName=q('playerName'),roomCode=q('roomCode'),createRoomButton=q('createRoom'),joinRoomButton=q('joinRoom'),actionMessage=q('actionMessage'),activeRoomCode=q('activeRoomCode'),roomCount=q('roomCount'),roomStatus=q('roomStatus'),playerList=q('playerList'),roomControls=q('roomControls'),readyButton=q('readyButton'),teamAButton=q('teamAButton'),teamBButton=q('teamBButton'),startGameButton=q('startGameButton'),lobbyHint=q('lobbyHint'),teamControls=q('teamControls'),modeControls=q('modeControls'),teamModeButton=q('teamModeButton'),survivalModeButton=q('survivalModeButton'),arenaTitle=q('arenaTitle'),arenaSubtitle=q('arenaSubtitle'),arenaOverlay=arenaTitle.closest('.overlay');
 function setBusy(b){createRoomButton.disabled=b;joinRoomButton.disabled=b;}
 function renderRoom(room,playerId){activeRoomCode.textContent=room?.code??'----';roomCount.textContent=`${room?.players?.length??0} / ${room?.maxPlayers??8}`;roomStatus.textContent=room?.status==='countdown'?'COUNTDOWN':room?.status==='started'?'ARENA ACTIVE':'LOBBY';
  if(!room?.players?.length){playerList.innerHTML='<div class="empty-room">No room joined yet.</div>';roomControls.hidden=true;arenaOverlay.hidden=false;return;}
  playerList.innerHTML=room.players.map((p,i)=>`<div class="player-row${p.id===playerId?' current-player':''}"><span class="player-index">${String(i+1).padStart(2,'0')}</span><strong>${esc(p.name)}</strong><span class="player-team">${room.mode==='survival'?'SURVIVAL':`TEAM ${esc(p.team)}`}</span><span class="player-ready ${p.ready?'is-ready':''}">${p.ready?'READY':'NOT READY'}</span><span class="player-host">${p.isHost?'HOST':''}</span></div>`).join('');
  const me=room.players.find(p=>p.id===playerId);roomControls.hidden=!me;if(!me)return;const locked=room.status!=='lobby';readyButton.disabled=locked;teamControls.hidden=room.mode!=='team';teamAButton.disabled=locked||me.team==='A';teamBButton.disabled=locked||me.team==='B';readyButton.textContent=me.ready?'CANCEL READY':'READY';readyButton.classList.toggle('active',me.ready);teamAButton.classList.toggle('active',me.team==='A');teamBButton.classList.toggle('active',me.team==='B');modeControls.hidden=!me.isHost;teamModeButton.disabled=locked;survivalModeButton.disabled=locked;teamModeButton.classList.toggle('active',room.mode==='team');survivalModeButton.classList.toggle('active',room.mode==='survival');startGameButton.hidden=!me.isHost;startGameButton.disabled=locked;
  if(locked){lobbyHint.textContent=`${room.mode==='survival'?'Survival':'Team'} match initialized. Camera follows the active target.`;arenaOverlay.hidden=true;}else{lobbyHint.textContent=me.isHost?'Host: choose mode, wait for READY, then start.':'Choose your setup and mark yourself ready.';arenaTitle.textContent='ARENA STANDBY';arenaSubtitle.textContent='World 5x5 // local viewport 1x1';arenaOverlay.hidden=false;}}
 return Object.freeze({playerName,roomCode,createRoomButton,joinRoomButton,readyButton,teamAButton,teamBButton,teamModeButton,survivalModeButton,startGameButton,setClientStatus:v=>clientStatus.textContent=v,setServerStatus:v=>serverStatus.textContent=v,setMessage:v=>actionMessage.textContent=v,setBusy,renderRoom});}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
